# Generated by Django 6.1 on 2026-08-14 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cafes/logos')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cafes/covers')),
                ('primary_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Primary color must be a hex color code', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
