# Generated by Django 6.1 on 2026-08-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafemodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/cafes/covers'),
        ),
        migrations.AlterField(
            model_name='cafemodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/cafes/logos'),
        ),
    ]
