# Generated by Django 6.1 on 2026-08-14 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_cafemodel_cover_image_alter_cafemodel_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafestaffmodel',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accounts.cafemodel'),
        ),
    ]
