# Generated by Django 6.1 on 2026-08-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_cafestaffmodel_cafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafestaffmodel',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cafestaffmodel',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
